INSERT INTO APP_SUPPLIERS(BUNAME,ID,USERREG,USERUPDATE) VALUES ('SALERNO',1,1,1);
INSERT INTO APP_SUPPLIERS(BUNAME,ID,USERREG,USERUPDATE) VALUES ('TESSITURA',2,1,1);
INSERT INTO APP_SUPPLIERS(BUNAME,ID,USERREG,USERUPDATE) VALUES ('LINOMANIA',3,1,1);
INSERT INTO APP_SUPPLIERS(BUNAME,ID,USERREG,USERUPDATE) VALUES ('SUGHERO',4,1,1);
INSERT INTO APP_SUPPLIERS(BUNAME,ID,USERREG,USERUPDATE) VALUES ('SCIARPA',5,1,1);
INSERT INTO APP_SUPPLIERS(BUNAME,ID,USERREG,USERUPDATE) VALUES ('CAPPELLI',6,1,1);
INSERT INTO APP_SUPPLIERS(BUNAME,ID,USERREG,USERUPDATE) VALUES ('SARTORIA',7,1,1);
INSERT INTO APP_SUPPLIERS(BUNAME,ID,USERREG,USERUPDATE) VALUES ('CHIACCHIERINO',8,1,1);